name: GitHub Actions Demo
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Testapp:
    runs-on: ubuntu-latest
    steps:
      - name: Recup du repo
        uses: actions/checkout@v2
      - name: list des fichiers
        run: ls
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: mvn test

