name: GitHub Actions Demo
on: [push]
jobs:
  Testapp:
    runs-on: ubuntu-latest
    steps:
      - name: Recup du repo
        uses: actions/checkout@v2
      - name: list des fichiers
        run: ls

